db:
  image: mongo:latest
  ports:
    - "27017:27017"
web:
  build: .
  command: npm start
  volumes:
    - .:/app
  ports:
    - "8080:8080"
  links:
    - db
  environment:
    NODE_ENV: production
    MONGO_URL: mongodb://db:27017
