version: '2'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  web:
    build: .
    image: docker-compose-example:v0.1
    command: npm start
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
    restart: always

